name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Login docker
      run: docker login -u sanraj2000 -p ${{ secrets.DOCKER_TOKEN }} docker.io
    
    - name: Build the Docker image
      run: docker build -t sanraj2000/book:latest -f Dockerfile .
      
     
   
      
    - name: Push the  docker image
      run: docker push sanraj2000/book:latest
      
    - name: Build the stack
      run: docker-compose up -d
      
    - name: Check the running container
      run: docker ps
      
    - name: Run a container
      run: docker run --rm -T sanraj2000/book:latest
      
   
    
