name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Login docker
      run: docker login -u sanraj2000 -p ${{ secrets.DOCKER_TOKEN }} docker.io
    
    - name: Build the Docker image
      run: docker build -t sanraj2000/book:latest -f Dockerfile .
      
     
   
      
    - name: Push the  docker image
      run: docker push sanraj2000/book:latest
      
    - name: Build the stack
      run: docker-compose up -d
      
    - name: Check the running container
      run: docker ps
      
    - name: All the containers
      run: docker ps -a
    
    - name: Check elasticsearch health
      run: |
          sleep 60
          curl -X GET http://localhost:9200/
      
   
          
    - name: Checking Post
      run: |
           sleep 60
           curl -X POST -H "Content-Type: application/json" \
               -d '{"id": "6", "bookname": "The Alchemist", "name": "Paulo Coelho", "created": "1988-05-16" }'\
               http://localhost:8080/api/add
           
    - name: Checking
      run: |
           sleep 60
           curl -X GET http://localhost:8080/api
