name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=book:latest
     
    - name: Login docker
      run: docker login -u sanraj2000 -p ${{ secrets.DOCKER_TOKEN }} 
      
    - name: Push the  docker image
      run: docker push book:latest
