name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag book:latest
    - name: Push the Docker image
      run: docker login -u sanraj2000 -p ${{ secrets.DOCKER_TOKEN }} && docker push book:latest
